from DBManager import DBManager

db_manager = DBManager("KAHOOT.db")
#db_manager.create_tables()
#db_manager.add_quiz(4, "Квіз про Україну", "деякий опис")
#db_manager.add_quiz(1, "Логіка", "Квіз на логіку")
#db_manager.add_question(4, 1, "У батьків є шість синів. У кожного сина є одна сестра. Скільки дітей у сім’ї?")
#db_manager.add_option(10, 12, False)
#db_manager.add_option(11, 7, True)
#db_manager.add_option(12, 6, False)
#db_manager.add_question(5, 1, "Яке число наступне у послідовності: 2, 4, 8, 16, ...?")
#db_manager.add_option(13, 32, True)
#db_manager.add_option(14, 36, False)
#db_manager.add_option(15, 17, False)
#db_manager.add_question(6, 1, "У вас є три коробки: перша важить 5 кг, друга – 10 кг, третя – 5 кг. Скільки разом важать дві найважчі коробки?")
#db_manager.add_option(16, 10, False)
#db_manager.add_option(17, 15, True)
#db_manager.add_option(18, 20, False)
db_manager.add_quiz(2, "Математичний квіз", "Перевірка твоїх знань з математики")
db_manager.add_question(7, 2, "Квадрат зі стороною 10 см поділено на чотири рівні квадрати. Яка площа одного з них?")
db_manager.add_option(19, "25 см²", True)
db_manager.add_option(20, "100 см²", False)
db_manager.add_option(21, "50 см²", False)
db_manager.add_question(8, 2, "Яке значення x задовольняє рівняння 3𝑥 = 81?" )
db_manager.add_option(22, 27, True)
db_manager.add_option(23, 9, False)
db_manager.add_option(24, 18, False)
db_manager.add_question(9, 2, "У трикутнику один з кутів дорівнює 60°, а інші два кути співвідносяться як 2:3. Знайдіть найбільший кут трикутника.")
db_manager.add_option(25, "90°", False)
db_manager.add_option(26, "75°", True)
db_manager.add_option(27, "120°", False)


#db_manager.add_question(1, 4, "Скільки областей в Україні?")
#db_manager.add_question(2, 4, "В якому році Україна стала незалежною?")
#db_manager.add_question(3, 4, "Хто є автором музики національного гімну України?")
##db_manager.add_option(1, 24, True)
#db_manager.add_option(2, 20, False)
#db_manager.add_option(3, 19, False)
#db_manager.add_option(4, 1990, False)
#db_manager.add_option(5, 1991, True)
#db_manager.add_option(6, 1993, False)
#db_manager.add_option(7, "Павло Чубинський", False)
#db_manager.add_option(8, "Михайло Вербицький ", True)
#db_manager.add_option(9, "Тарас Шевченко", False)

#print(db_manager.get_quizzes())
#print(db_manager.get_questions(4))
#print(db_manager.get_options())